#!/bin/sh

# how to call:
# ytAudio "Artist" "Album" "Song name"
# or: ytAudio "Artist" "Song name"
# or: ytAudio URL
#
# TODO: Support single songs

filetype="mp3"
YTDL="yt-dlp"
TMPDIR="/mnt/nas/tmp"
DESTDIR="/mnt/nas/Music"
declare ARTIST
declare ALBUM
declare COVER
declare HASCOVER

usage()
{
	echo "Usage:"
	echo "$(basename $0) -a ARTIST -A ALBUM [-c ALBUMCOVER] [-d DESTDIR] [-t TMPDIR] URL "
	# echo "-n: Don't recode to ogg"
}

check_depends() {
	if ! command -v $1 >/dev/null 2>&1; then
		echo "Error: $1 not found"
		exit 1
	fi

}

download_audio(){
    $YTDL -i -f bestaudio -o "%(playlist_index)s - %(title)s.%(ext)s" "$1"
}

recode_audio(){
    find ./ -maxdepth 1 -type f \( -name "*.webm" -or -name "*mp3" -or -name "*.m4a" \) -execdir sh -c '
    oldname="{}"; 
    newname="${oldname%.*}.mp3"
    ffmpeg -i "$oldname" "$newname"
    ' \;
}

rename_tag_and_place(){ # renames all files and moves to directory $artist/$album ($1/$2)
	artist="$1"
	album="$2"
	dir=""
	if [ -n "$album" ]
	then
		dir="$artist/$album"
	else
		dir="$artist"
	fi
	mkdir -p "$dir"
	for file in *.$filetype
	do
		echo "$file"
        # Regex explanation: remove numbers in front  | remove artist in front | remove brackets at the end
		title=$(echo "$file" | sed -r "s/.. - //" | sed -r "s/(.+?) ?- ?(.+)/\2/" | sed -r "s/([^\(]*).*/\1/" | sed -r "s/[ \t]+$//" | sed -r "s/\..*$//")
        num="${file:0:2}"
		echo "Title: $title"
		echo "Number: $num"
		id3v2 --artist "$artist" --song "$title" --album "$album" -T $num "$file"
		id3v2 -l "$file"
		mv "$file" "$dir/$title.mp3"
	done
	if [ ! -z $HASCOVER ]; then
		mv Folder.jpg "$dir"
	fi
}

move_audio(){
	echo "Copying to the right directories"
	# find -mindepth 1 -maxdepth 1 -type d -print -execdir cp "{}" /mnt/nas/moveToPhone -r \;
	find -mindepth 1 -maxdepth 1 -type d -print -execdir cp "{}" "$DESTDIR" -r \;
}

check_depends $YTDL
check_depends id3v2
check_depends ffmpeg

# declare SINGLE=false

while getopts 'ha:A:c:t:d:s' c
do
	case $c in
		h) usage; exit ;;
		a) ARTIST="$OPTARG" ;;
		A) ALBUM="$OPTARG" ;;
		c) COVER="$OPTARG"; HASCOVER=1; ;;
		t) TMPDIR="$OPTARG" ;;
		d) DESTDIR="$OPTARG" ;;
		s) SINGLE=true ;;
	esac
done

shift $((OPTIND-1))

# if [ ( -z "asdf" ) -o ( -z "$ALBUM" ) ]
if [ -z "$ARTIST" -o -z "$ALBUM" ]
then
	echo "Please provide an artist and album"
	echo "$ARTIST"
	echo "$ALBUM"
	usage
	exit 2
fi

if [ ! -d "$DESTDIR" ]; then
	echo "Destination directory $DESTDIR doesn't exists"
	exit 1
fi

URL="$1"

echo "Downloading playlist $URL"

TMPLOC=$(mktemp -p "$TMPDIR" -d)
if [ -z "$TMPLOC" ]
then
	echo "Could not create tempdir"
	exit 1
fi
cd "$TMPLOC"
pwd
download_audio "$URL"
if [ ! -z $HASCOVER ]
then
    wget "$COVER" -O Folder.jpg --no-verbose
fi
recode_audio
rename_tag_and_place "$ARTIST" "$ALBUM"
move_audio
pwd
